# Generated by Django 2.0.4 on 2018-04-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180430_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
